global-styling:
  version: 1.0
  header: true
  css:
    theme:
      dist/style.css: {}
  js:
    dist/00-base/global.min.js.gz: { minified: true }
  dependencies:
    - core/drupal
    - core/drupalSettings
    - core/jquery
    - core/jquery.once
accordion:
  version: 1.0
  js:
    dist/03-organisms/00-paragraphs/accordion/accordion.min.js.gz: { minified: true }
featherlight:
  version: 1.7.13
  css:
    theme:
      components/js/featherlight/featherlight.css: {}
      components/js/featherlight/featherlight.gallery.css: {}
  js:
    components/js/featherlight/featherlight.min.js: { minified: true }
    components/js/featherlight/featherlight.gallery.min.js: { minified: true }
forms:
  version: 1.0
  js:
    dist/01-atoms/03-forms/_forms.min.js.gz: { minified: true }
galleries:
  version: 1.0
  js:
    dist/03-organisms/00-paragraphs/gallery/gallery.min.js.gz: { minified: true }
menu-block:
  version: 1.0
  js:
    dist/02-molecules/menus/menu-block/_menu-block.min.js.gz: { minified: true }
modal:
  version: 1.0
  js:
    dist/05-miscellaneous/modal.min.js.gz: { minified: true }
object-fit:
  version: 1.0
  js:
    dist/05-miscellaneous/_object-fit.min.js.gz: { minified: true }
pager:
  version: 1.0
  js:
    dist/02-molecules/pagers/_pager.min.js.gz: { minified: true }
search-block:
  version: 1.0
  js:
    dist/02-molecules/blocks/search/search-block.min.js.gz: { minified: true }
search-page:
  version: 1.0
  js:
    dist/04-elements/_search.min.js.gz: { minified: true }
select:
  version: 4.0.3
  css:
    theme:
      components/js/select2/select2.min.css: { minified: true }
  js:
    components/js/select2/select2.min.js: { minified: true }
    dist/01-atoms/03-forms/_forms.min.js.gz: { minified: true }
slick:
  version: 1.8.1
  css:
    theme:
      components/js/slick/slick.css: {}
      components/js/slick/slick-theme.css: {}
  js:
    components/js/slick/slick.min.js: { minified: true }
table:
  version: 1.0
  js:
    components/js/stacktable/stacktable.min.js: { minified: true }
    dist/01-atoms/04-tables/tables.min.js.gz: { minified: true }
user:
  version: 1.0
  js:
    dist/04-elements/_user-dashboard.min.js.gz: { minified: true }
    https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js: { type: external, minified: true, preprocess: false }
views:
  version: 1.0
  js:
    dist/03-organisms/01-views/_views.min.js.gz: { minified: true }
  dependencies:
    - core/underscore
widgets:
  version: 1.0
  js:
    dist/03-organisms/00-paragraphs/_widgets.min.js.gz: { minified: true }
  dependencies:
    - core/underscore
fonts:
  css:
    theme:
      https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700: { type: external, preprocess: false }
