global-styling:
  version: 1.0
  css:
    theme:
      dist/style.css: { minified: true }
  js:
    dist/00-base/global.min.js.gz: { minified: true }
accordion:
  version: 1.0
  js:
    dist/03-organisms/00-paragraphs/accordion/accordion.min.js.gz: { minified: true }
anchor:
  version: 1.0
  js:
    dist/03-organisms/00-paragraphs/anchor/anchor.min.js.gz: { minified: true }
featherlight:
  version: 3.0
  css:
    theme:
      https://cdn.rawgit.com/noelboss/featherlight/1.7.12/release/featherlight.min.css: { type: external, minified: true, preprocess: false }
      https://cdn.rawgit.com/noelboss/featherlight/1.7.12/release/featherlight.gallery.min.css: { type: external, minified: true, preprocess: false }
  js:
    https://cdn.rawgit.com/noelboss/featherlight/1.7.12/release/featherlight.min.js: { type: external, minified: true, preprocess: false }
    https://cdn.rawgit.com/noelboss/featherlight/1.7.12/release/featherlight.gallery.min.js: { type: external, minified: true, preprocess: false }
forms:
  version: 1.0
  js:
    dist/01-atoms/03-forms/_forms.min.js.gz: { minified: true }
galleries:
  version: 1.0
  js:
    dist/03-organisms/00-paragraphs/gallery/gallery.min.js.gz: { minified: true }
media-js:
  version: 1.0
  js:
    dist/02-molecules/media/_media.min.js.gz: { minified: true }
modal:
  version: 1.0
  js:
    dist/05-miscellaneous/modal.min.js.gz: { minified: true }
object-fit:
  version: 1.0
  js:
    dist/05-miscellaneous/_object-fit.min.js.gz: { minified: true }
search-block:
  version: 1.0
  js:
    dist/02-molecules/blocks/search/search-block.min.js.gz: { minified: true }
search-page:
  version: 1.0
  js:
    dist/04-elements/_search.min.js.gz: { minified: true }
select:
  version: 3.0
  css:
    theme:
      /modules/custom/citizen_custom/js/select2/select2.min.css: { minified: true }
  js:
    /modules/custom/citizen_custom/js/select2/select2.min.js: { minified: true }
    /modules/custom/citizen_custom/js/select.js: {}
slick:
  version: 3.0
  css:
    theme:
      https://cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.css: { type: external, preprocess: false }
      https://cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css: { type: external, preprocess: false }
  js:
    https://cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.min.js: { type: external, minified: true, preprocess: false, attributes: { async: true } }
table:
  version: 1.0
  js:
    components/js/stacktable/stacktable.min.js: { minified: true }
    dist/01-atoms/04-tables/tables.min.js.gz: { minified: true }
user:
  version: 1.0
  js:
    dist/04-elements/_user-dashboard.min.js.gz: { minified: true }
    https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js: { type: external, minified: true, preprocess: false }
views:
  version: 1.0
  js:
    dist/03-organisms/01-views/_views.min.js.gz: { minified: true }
  dependencies:
    - core/underscore
fonts:
  css:
    theme:
      https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700: { type: external, preprocess: false }
