global-styling:
  version: 1.0
  header: true
  css:
    theme:
      dist/style.css: {}
  js:
    components/_patterns/05-assembly/site.js: {}
  dependencies:
    - core/drupal
    - core/drupalSettings
    - core/jquery
    - core/jquery.once
accordion:
  version: 1.0
  js:
    components/_patterns/03-composites/00-paragraphs/accordion/accordion.js: {}
featherlight:
  version: 1.7.13
  css:
    theme:
      components/js/featherlight/featherlight.css: {}
      components/js/featherlight/featherlight.gallery.css: {}
  js:
    components/js/featherlight/featherlight.min.js: { minified: true }
    components/js/featherlight/featherlight.gallery.min.js: { minified: true }
forms:
  version: 1.0
  js:
    components/_patterns/01-parts/03-forms/_forms.js: {}
galleries:
  version: 1.0
  js:
    components/_patterns/03-composites/00-paragraphs/gallery/gallery.js: {}
layout:
  version: 1.0
  js:
    components/_patterns/03-composites/02-layout/02-layout-builder/layout.js: {}
menu-block:
  version: 1.0
  js:
    components/_patterns/02-chunks/menus/menu-block/_menu-block.js: {}
modal:
  version: 1.0
  js:
    components/_patterns/02-chunks/modals/modal.js: {}
object-fit:
  version: 1.0
  js:
    components/_patterns/05-assembly/_object-fit.js: {}
pager:
  version: 1.0
  js:
    components/_patterns/02-chunks/pagers/_pager.js: {}
search-block:
  version: 1.0
  js:
    components/_patterns/02-chunks/blocks/search/search-block.js: {}
search-page:
  version: 1.0
  js:
    components/_patterns/04-units/_search.js: {}
select:
  version: 4.0.3
  css:
    theme:
      components/js/select2/select2.min.css: { minified: true }
  js:
    components/js/select2/select2.min.js: { minified: true }
    components/_patterns/01-parts/03-forms/_forms.js: {}
slick:
  version: 1.8.1
  css:
    theme:
      components/js/slick/slick.css: {}
      components/js/slick/slick-theme.css: {}
  js:
    components/js/slick/slick.min.js: { minified: true }
table:
  version: 1.0
  js:
    components/js/stacktable/stacktable.min.js: { minified: true }
    components/_patterns/01-parts/04-tables/_tables.js: {}
user:
  version: 1.0
  js:
    components/_patterns/04-units/_user-dashboard.js: {}
    https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js: { type: external, minified: true, preprocess: false }
views:
  version: 1.0
  js:
    components/_patterns/03-composites/01-views/_views.js: {}
  dependencies:
    - core/underscore
widgets:
  version: 1.0
  js:
    components/_patterns/03-composites/00-paragraphs/_widgets.js: {}
  dependencies:
    - core/underscore
fonts:
  css:
    theme:
      https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700: { type: external, preprocess: false }

